stages:
  - verify
  - set-tag
  - build-images

before_script:
  - export DOCKER_USER=$CI_BUILD_DOCKER_USER
  - export DOCKER_PASS=$CI_BUILD_TOKEN
  - export DOCKER_URL=$CI_BUILD_DOCKER_URL


include:
  - local: ci/kun-data-discover.gitlab-ci.yml
  - local: ci/kun-frontend.gitlab-ci.yml
  - local: kun-metadata.gitlab-ci.yml