server:
  port: ${DATA_PLATFORM_PORT:8081}

workflow:
  enabled: true
  baseUrl: http://${WORKFLOW_HOST}:${WORKFLOW_PORT}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_PG_IP}:${DB_PG_PORT}/dataplatform?stringtype=unspecified
    username: ${DB_PG_USERNAME}
    password: ${DB_PG_PASSWORD}

  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:sql
    table: flyway_kun_app_schema_history
    schemas: public
    baseline-on-migrate: true
    baseline-version: 0

security:
  base-url: http://${SECURITY_HOST}:${SECURITY_PORT}/kun/api/v1

dubbo:
  application:
    name: data-platform
    id: data-platform
  registry:
    address: redis://localhost:6379
  protocol:
    name: dubbo
    port: -1

zhongda:
  host: http://zhongda.miotech.com:8000
  token: ZXGfFpQs7ubLBPJYCZVHn
  notify-group: kun

redis:
  host: ${DB_REDIS_IP}
  notify-channel: kun-notify
