server:
  port: ${DATA_PLATFORM_PORT:8081}

workflow:
  enabled: true
  baseUrl: http://${WORKFLOW_HOST}:${WORKFLOW_PORT}
  variableNamespace: dataplatform

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_PG_IP}:${DB_PG_PORT}/dataplatform?stringtype=unspecified
    username: ${DB_PG_USERNAME}
    password: ${DB_PG_PASSWORD}

  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:sql
    table: flyway_kun_app_schema_history
    schemas: public

security:
  base-url: http://${SECURITY_HOST}:${SECURITY_PORT}/kun/api/v1

redis:
  host: ${DB_REDIS_IP}
  notify-channel: kun-notify

management:
  health:
    elasticsearch:
      enabled: false
    ldap:
      enabled: false

notify:
  systemDefault:
    # Allowed trigger types: ON_SUCCESS, ON_FAIL, ON_FINISH, NEVER
    triggerType: ON_FAIL
    userConfigJson: '[{"notifierType": "WECOM"}]'
  email:
    smtpHost: ${SMTP_HOST}
    smtpPort: ${SMTP_PORT:465}
    smtpUsername: ${SMTP_USERNAME}
    smtpPassword: ${SMTP_PASSWORD}
    emailFrom: ${EMAIL_FROM:noreply@miotech.com}
    emailFromName: ${EMAIL_FROM_NAME:kun-robot}

  zhongda:
    host: http://zhongda.miotech.com:8000
    token: ZXGfFpQs7ubLBPJYCZVHn
    notify-group: kun
