server:
  port: ${DATA_PLATFORM_PORT:8081}

workflow:
  enabled: true
  baseUrl: http://${WORKFLOW_HOST}:${WORKFLOW_PORT}
  variableNamespace: dataplatform

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_PG_IP}:${DB_PG_PORT}/dataplatform?stringtype=unspecified
    username: ${DB_PG_USERNAME}
    password: ${DB_PG_PASSWORD}

  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:sql
    table: flyway_kun_app_schema_history
    schemas: public

security:
  base-url: http://${SECURITY_HOST}:${SECURITY_PORT}/kun/api/v1

redis:
  host: ${DB_REDIS_IP}
  notify-channel: kun-notify

management:
  health:
    elasticsearch:
      enabled: false
    ldap:
      enabled: false

# Notification configurations items
notify:
  # System default configurations to be applied for default task definitions.
  systemDefault:
    # Allowed trigger types: ON_SUCCESS, ON_FAIL, ON_FINISH, NEVER
    triggerType: ON_FAIL
    userConfigJson: '[{"notifierType": "WECOM"}]'
  # Email notifier settings
  email:
    # Host of SMTP server to connect
    smtpHost: ${SMTP_HOST}
    # Port of SMTP server to connect
    smtpPort: ${SMTP_PORT:465}
    # Username of SMTP server to connect
    smtpUsername: ${SMTP_USERNAME}
    # Password of SMTP server to connect
    smtpPassword: ${SMTP_PASSWORD}
    # Connection transmission security protocol. Available options: auto (default), ssl_tls, starttls, none.
    # When set to "auto", the application will automatically determine which security protocol to use by smtp port number.
    smtpSecurity: ${SMTP_SECURITY_PROTOCOL:auto}
    # Displayed email address of sending from
    emailFrom: ${EMAIL_FROM:noreply@miotech.com}
    # Displayed name of sending from
    emailFromName: ${EMAIL_FROM_NAME:kun-robot}

  zhongda:
    host: http://zhongda.miotech.com:8000
    token: ZXGfFpQs7ubLBPJYCZVHn
    notify-group: kun
