
# workflow:
#   rules:
#     - changes:
#       - kun-metadata/*

verify-kun-data-discover-test:
  stage: verify
  image: gradle:6.5.0-jdk8
  except:
    - master
    - release
    - production
    - tags
  allow_failure: false
  script:
    - ./gradlew test -p kun-data-discover
    - ./gradlew check -p kun-data-discover
  only:
    changes:
      - kun-data-discover/*

verify-kun-data-discover-sonar:
  stage: verify
  image: mioyingtech/gradle-sonar:0.1-build
  except:
    - release
    - production
    - tags
  allow_failure: false
  script:
    - >
      if [ $CI_COMMIT_REF_NAME == "master" ]; then 
          ./gradlew sonarqube -p kun-data-discover -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_TOKEN -Dsonar.analysis.mode=publish -Dsonar.issuesReport.html.enable=true -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.projectKey=com.miotech:kun-data-discover -Dsonar.projectName='kun-data-discover' -Dsonar.sources=./kun-data-discover/src/main -Dsonar.sourceEncoding=UTF-8 -Dsonar.java.binaries=./kun-data-discover/build;
      else ./gradlew sonarqube -p kun-data-discover -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_TOKEN -Dsonar.analysis.mode=preview -Dsonar.issuesReport.html.enable=true -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.projectKey=com.miotech:kun-data-discover -Dsonar.projectName='kun-data-discover' -Dsonar.sources=./kun-data-discover/src/main -Dsonar.sourceEncoding=UTF-8 -Dsonar.java.binaries=./kun-data-discover/build;  
      fi
  only:
    changes:
      - kun-data-discover/*

.kun-data-discover-build-job:
  stage: build-images
  tags:
    - build
  script:
    - ./gradlew :kun-data-discover:bootJars
    - mkdir -p /builds/artifacts/kun-data-discover/${CI_COMMIT_REF_NAME}/
    - cp kun-data-discover/build/libs/*.jar /builds/artifacts/kun-data-discover/${CI_COMMIT_REF_NAME}/
  only:
    refs:
      - master
      - release
      - tags
    changes:
      - kun-data-discover/*

kun-data-discover-build:
  extends: .kun-data-discover-build-job
  image: gradle:6.5.0-jdk8
  tags:
    - docker-push
  script:
    - mkdir -p build/libs/
    - rsync -vzrtopg --progress -e ssh root@$CI_RUNNER_SERVER:/miotech/artifacts/kun-data-discover/${CI_COMMIT_REF_NAME}/ build/libs/
    - export TAG_DATA_DISCOVERY=$CI_COMMIT_REF_NAME
    - ./gradlew :kun-data-discover:buildPushImage